// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:b1fa719b-201e-448b-85c2-ab25fd71d1b9",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_3zqnUJ6HN",
    "aws_user_pools_web_client_id": "u3bd874dkbqnf2ih8c3v20chq",
    "oauth": {},
    "aws_user_files_s3_bucket": "miypshidemobucket-develop",
    "aws_user_files_s3_bucket_region": "ap-northeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "miyoshidemoapi",
            "endpoint": "https://nlv3xp2icf.execute-api.ap-northeast-1.amazonaws.com/develop",
            "region": "ap-northeast-1"
        }
    ],
    "aws_content_delivery_bucket": "miyoshidemohostingbucket-develop",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "https://d233rwgf32clmx.cloudfront.net"
    
};

export default awsmobile;

